.TH pass-checkstrength 1 "2018 August 14" "Version 0.0.1" "User Commands"

.SH NAME
pass-checkstrength - a password-store extension to check the strength of passwords

.SH SYNOPSIS
.B pass
checkstrength

.SH DESCRIPTION

.B pass-checkstrength
is an extension for
.BR pass(1)
that allows users to check the strength of their passwords.

.SH COMMANDS
.TP
\fBcheckstrength\fP
.br
Check all the passwords with libcrack2. Prints out the offending file names with the reason.

.SH SEE ALSO
.BR pass (1)

.SH AUTHOR
jcmuller

.SH HOME
.I https://github.com/jcmuller/pass-checkstrength

.SH REPORTING BUGS
.I https://github.com/jcmuller/pass-checkstrength/issues

.SH LICENSE
Copyright \(co 2017 jcmuller.
.PP
License MIT: <https://opensource.org/licenses/MIT>.
.br
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
